### ISSUE TITLE
Error with plugins when starting ScreenCloud

### ISSUE THREAD

**Issue by dbermond** [olav-st/screencloud#214]
I'm having the following error when _starting_ ScreenCloud. It happens with the git master version and also with the 1.2.0 release version.

When using the git master version compiled with Qt5 interface the error is (username intentionally left blank):
![screencloud-pythonqt-error1](https://cloud.githubusercontent.com/assets/16004942/17066396/4d8e0556-501d-11e6-861a-5603d4e76217.png)
![screencloud-pythonqt-error2](https://cloud.githubusercontent.com/assets/16004942/17061858/def60438-5006-11e6-8050-e6a198b7cd6e.png)

Console output from git master version:

```
$ screencloud
[WARN] "Error while parsing script file /home/user/.local/share/screencloud/ScreenCloud/plugins/ftp/main.py"
[WARN] "Error while parsing script file /home/user/.local/share/screencloud/ScreenCloud/plugins/imgur/main.py"
[WARN] "Error while parsing script file /home/user/.local/share/screencloud/ScreenCloud/plugins/sftp/main.py"
[WARN] "Error while parsing script file /home/user/.local/share/screencloud/ScreenCloud/plugins/dropbox/main.py"
[WARN] "Error while parsing script file /home/user/.local/share/screencloud/ScreenCloud/plugins/file/main.py"
[INFO] "Loaded 5 plugin(s)"
[INFO] "Using icon from theme: oxygen"
[WARN] "Failed to call isConfigured() in ImgurUploader"
[WARN] "Failed to call isConfigured() in SFTPUploader"
[WARN] "Failed to call isConfigured() in FileUploader"
[WARN] "Failed to call isConfigured() in FTPUploader"
[WARN] "Failed to call isConfigured() in DropboxUploader"
[INFO] "Plugin update check. Has version 1.3 of 'dropbox'. Latest is 1.3"
[INFO] "Plugin update check. Has version 1.6 of 'imgur'. Latest is 1.6"
[INFO] "Plugin update check. Has version 1.4 of 'ftp'. Latest is 1.4"
[INFO] "Plugin update check. Has version 1.4 of 'sftp'. Latest is 1.4"
[INFO] "Plugin update check. Has version 1.1 of 'file'. Latest is 1.1"
[INFO] "Plugin update check. Has version 1.3 of 'dropbox'. Latest is 1.3"
[INFO] "Plugin update check. Has version 1.6 of 'imgur'. Latest is 1.6"
[INFO] "Plugin update check. Has version 1.4 of 'ftp'. Latest is 1.4"
[INFO] "Plugin update check. Has version 1.4 of 'sftp'. Latest is 1.4"
[INFO] "Plugin update check. Has version 1.1 of 'file'. Latest is 1.1"
```

When using the 1.2.0 release version, the error is (username intentionally left blank):
![screencloud-release-error](https://cloud.githubusercontent.com/assets/16004942/17066415/5bafaaa4-501d-11e6-9343-8d20e3689412.png)
![screencloud-release-error2](https://cloud.githubusercontent.com/assets/16004942/17065363/cd5e7280-5017-11e6-8459-dc3d68d5d3af.png)
Console output from 1.2.0 release version:

```
$ screencloud 
[WARN] "Error while parsing script file /home/user/.local/share/data/screencloud/ScreenCloud/plugins/sftp/main.py" 
[INFO] "Loaded 5 plugin(s)" 
[WARN] "Audio format not supported by backend. Trying nearest format." 
[WARN] "Error while creating audio output. Code: 1 Device: " 
[INFO] "Using bundled icon: :/systray/trayicon-gray.svg" 
[WARN] "Failed to call isConfigured() in SFTPUploader"
```

With git master version (Qt5) it shows these two dialogs for every plugin that I have installed: ftp, sftp, imgur, dropbox and file. The mentioned installed plugins cannot be used. They all give a similiar dialog error when trying to configure them in `Preferences`-> `Online Services`->`Settings`. I can save screenshots only to Clipboard and directly to ScreenClound online service.

When using the 1.2.0 release version this error occurs only with the sftp plugin. It gives a similiar dialog error when trying to configure it in `Preferences`-> `Online Services`->`Settings`. All other plugins are working.

**ScreenCloud:** version git master (currently at version 1.2.0.r109.gc328b34) and version 1.2.0 release
**OS:** Arch Linux x86_64
**Desktop:** Plasma 5.7.2
**gcc:** 6.1.1
**python:** 3.5.2
**python2:** 2.7.12
**qt5-base:** 5.7.0
**pythonqt-qt5:** 3.1
**python-pyqt5:** 5.6
**qt4:** 4.8.7
**python-pyqt4:** 4.11.4

Any help would be appreciated.
Thank you.

**Comment by olav-st** [comment]
Thanks for the detailed report!

This is a problem with the newest version of PythonQt and not ScreenCloud itself. It seems that the QtUiTools wrappers were removed. I've asked the PythonQt author if the change was intentional or not: https://sourceforge.net/p/pythonqt/discussion/631393/thread/28b3bb01/.

**Comment by bermond** [comment]
Thank you for your reply and support Olav.

I compiled PythonQt using the latest SVN version (actually r438, after the upstream re-addition of QtUiTools wrappers) and recompiled screenclound git master version (Qt5) but the issue partially persists. In screencloud git master version all plugins are working now, except for sftp.

Screenshots of error dialog when staring screenclout git master:
![screencloud-git-new-error1-upload](https://cloud.githubusercontent.com/assets/16004942/17111807/933dad64-5279-11e6-8b39-048acfb32f3b.png)
![screencloud-git-new-error2](https://cloud.githubusercontent.com/assets/16004942/17111809/97e966c8-5279-11e6-8b0e-a36d3b5d728b.png)

New console output of git master version:
```
$ screencloud
[WARN] "Error while parsing script file /home/daniel/.local/share/screencloud/ScreenCloud/plugins/sftp/main.py"
[INFO] "Loaded 5 plugin(s)"
[INFO] "Using icon from theme: oxygen"
[WARN] "Failed to call isConfigured() in SFTPUploader"
[INFO] "Plugin update check. Has version 1.3 of 'dropbox'. Latest is 1.3"
[INFO] "Plugin update check. Has version 1.6 of 'imgur'. Latest is 1.6"
[INFO] "Plugin update check. Has version 1.4 of 'ftp'. Latest is 1.4"
[INFO] "Plugin update check. Has version 1.4 of 'sftp'. Latest is 1.4"
[INFO] "Plugin update check. Has version 1.1 of 'file'. Latest is 1.1"
[INFO] "Plugin update check. Has version 1.3 of 'dropbox'. Latest is 1.3"
[INFO] "Plugin update check. Has version 1.6 of 'imgur'. Latest is 1.6"
[INFO] "Plugin update check. Has version 1.4 of 'ftp'. Latest is 1.4"
[INFO] "Plugin update check. Has version 1.4 of 'sftp'. Latest is 1.4"
[INFO] "Plugin update check. Has version 1.1 of 'file'. Latest is 1.1"
```

The sftp plugin cannot be configured in `Preferences`->`Online Services`->`Settings`, producing a similiar dialog error.

When using screencloud version 1.2.0 release, the issue remains the same (problem occurs only with sftp plugin as in initial description).

As you can see, the issue seems to be restricted to the sftp plugin.

Also, I tried to apply a patch over PythonQt 3.1 using the SVN commit that re-added the QtUiTools wrappers. By doing this, the issue is almost the same with screencloud git master version, but now with sftp and dropbox plugins being affected, making both unusable, and screencloud version 1.2.0 remains with the same sftp problem.

**Comment by olav-st** [comment]
You probably don't have PyCrypto installed. Try installing `python-crypto` or `python2-crypto`.

**Comment by bermond** [comment]
I had `python-crypto` installed. Installing `python2-crypto` doesn't solve the sftp plugin issue.

Installing `python-paramiko` and `python2-paramiko` doesn't help either.

**Comment by jeserkin** [comment]
After recent update (yesterday) the PC on startup through following error: https://www.dropbox.com/s/vtgdm0yktwwv1g3/2016-08-13_165224.png?dl=0.
It is a bit annoying, feels like plugins are shipped without any testing whatsoever.

**Comment by jeserkin** [comment]
After recent update (yesterday), the app on startup thoughs following errors:
![2016-08-13_165224](https://cloud.githubusercontent.com/assets/183512/17643596/8f45786a-6177-11e6-9e7a-bc07c43bf9ed.png)
![2016-08-13_165958](https://cloud.githubusercontent.com/assets/183512/17643597/92bef228-6177-11e6-98a6-f686d3c79558.png)
It is a bit annoying, feels like plugins are not tested before they are shipped.

**Comment by bermond** [comment]
> After recent update (yesterday), the app on startup thoughs following errors:

I'm having this same issue since yesterday after the dropbox plugin got updated from version 1.3 to 1.5.

**Comment by furai** [comment]
I'm having the same issues as people above. I've just installed screencloud on ubuntu 16.04 using new repo entries. No plugins seem to work. 

Also the rectangle selection lags a lot.

**Comment by jeserkin** [comment]
Temproray workaround to those who updated to latest plugins and can not use dropbox:
1. Download previoud plugin version https://github.com/olav-st/screencloud-plugins/blob/467f90f44c3e2a33205c7c4d56bc31a200584c7f/dropbox/current.zip
2. Close **ScreenCloud**
3. In `AppData` directory open dropbox plugin directory e.g.: `AppData\Local\screencloud\ScreenCloud\plugins\dropbox`
4. Remove all files from that directory and extract those, that where in `current.zip` file download on step 1.
5. Start *ScreenCloud* and do not update plugin for now.
6. Profit!

**Comment by olav-st** [comment]
> It is a bit annoying, feels like plugins are not tested before they are shipped.

Because they aren't very thoroughly tested. I was working on v1.3.0 of ScreenCloud when I updated the plugin. The new version uses Python 3 on most systems so that's why I didn't encounter this error. Updating to 1.3.0 should fix the problem for you.

**Comment by pfoo** [comment]
Just got this error after upgrading to 1.3.0 and reinstalled sftp plugin : 

> Error in file: /home/pfoo/.local/share/screencloud/ScreenCloud/plugins/sftp/main.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/pfoo/.local/share/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/home/pfoo/.local/share/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/transport.py", line 50, in <module>
    from paramiko.dsskey import DSSKey
  File "/home/pfoo/.local/share/screencloud/ScreenCloud/plugins/sftp/modules/paramiko/dsskey.py", line 26, in <module>
    from Crypto.PublicKey import DSA
ImportError: No module named Crypto.PublicKey

then

> Failed to call SFTPUploader.isConfigured()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name SFTPUploader
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'SFTPUploader' is not defined

**Comment by bermond** [comment]
> Because they aren't very thoroughly tested. I was working on v1.3.0 of ScreenCloud when I updated the plugin. The new version uses Python 3 on most systems so that's why I didn't encounter this error. Updating to 1.3.0 should fix the problem for you.

I'm using git master version (currently at version 1.3.0.r1.g38937c5) and python 3.5.2. Still, the issue remains with sftp and dropbox plugins.



> Just got this error after upgrading to 1.3.0 and reinstalled sftp plugin

Good to know that I'm not alone with the issue in sftp plugin.

**Comment by CleverWhiteWolf** [comment]
I have the same issue with SFTP plugin on Kubuntu 16.04 with v1.3.0 of ScreenCloud.
Also I have the issue with SFTP plugin on Windows 7 even with fresh install of the program.
I get the following error during attempt to upload screenshot into SFTP server:
![screencloud](https://cloud.githubusercontent.com/assets/5293057/17708075/c696410a-63fc-11e6-8e44-a64dd8915383.jpg)

This error I see when I try to open settings of SFTP plugin:
![screencloud2](https://cloud.githubusercontent.com/assets/5293057/17708125/0c6a88e4-63fd-11e6-947f-1ab59ac4b105.jpg)

**Comment by mkody** [comment]
I'm getting the same `ImportError: No module named 'Crypto.PublicKey'` error, which gives me an another error afterwards: `NameError: name 'SFTPUploader' is not defined`
This happens when I installed the SFTP plugin or when launching Screencloud. 
> https://gist.github.com/mkody/b19937e079441b5d39576b0f4bf1ac22

Typing `from Crypto.PublicKey import DSA` on an interactive Python shell doesn't return any error.
![1471368503](https://cloud.githubusercontent.com/assets/843787/17709001/a0fdb028-63e7-11e6-9473-0a0b47f6168a.png)

OS: `Arch Linux, x86_64, 4.6.4-1-ARCH #1 SMP PREEMPT`
Python: `Python 3.5.2`
pip: `pip 8.1.2 from /usr/lib/python3.5/site-packages (python 3.5)`

**Comment by MyTheValentinus** [comment]
Hello, after update to screecloud 1.3 error come back.
Do you have solution ? I have installed screendcloud with your repo.

**Comment by jeserkin** [comment]
@MyTheValentinus if you are looking for any solution, then did even care to read my previous comment?

**Comment by OnkelTem** [comment]
I also had problems with running SC, then I just deleted `~/.config/screencloud/ScreenCloud.conf` and  restarted SC. All the issues has gone.

**Comment by pfoo** [comment]
For ubuntu, copying /usr/lib/python2.7/dist-packages/Crypto/ to ~/.local/share/screencloud/ScreenCloud/plugins/sftp/modules/ fixes the issue for now. Not working if using the python3 version of Crypto (but the error changes). Could be related, I thought screencloud 1.3 was using python 3 ?

**Comment by MyTheValentinus** [comment]
Hello @pfoo,
Thank for your quick solution.
I'm waiting @olav-st final solution to work with python 3.
Thank

**Comment by OnkelTem** [comment]
@MyTheValentinus mate why are you doing that? I just said how I've fixed my issue, nothing more. I'm not a model walking a catwalk for your evaluation!

**Comment by olav-st** [comment]
For the dropbox plugin, see https://github.com/olav-st/screencloud/issues/224. I've pushed a fix.

**Comment by cgrimal** [comment]
Hi @olav-st !

I'm running screencloud (1.3, but I tried with 1.2 as well) on Ubuntu 16.04 and I'm still struggling with the sftp plugin and the "No module named Crypto.PublicKey", which is how we share screenshots in my team. I've tried many workarounds, but still no luck... :'(

Do you have a solution for poor guys like me?

Thanks!
Clément

**Comment by mzubairharoon** [comment]
Hi, I'm getting this error with SC dropbox service.

`Error in file: /home/zubair/.local/share/screencloud/ScreenCloud/plugins/dropbox/main.py
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "/home/zubair/.local/share/screencloud/ScreenCloud/plugins/dropbox/modules/dropbox/__init__.py", line 3, in <module>
    from .dropbox import __version__, Dropbox, DropboxTeam, create_session
  File "/home/zubair/.local/share/screencloud/ScreenCloud/plugins/dropbox/modules/dropbox/dropbox.py", line 19, in <module>
    from . import stone_serializers
  File "/home/zubair/.local/share/screencloud/ScreenCloud/plugins/dropbox/modules/dropbox/stone_serializers.py", line 23, in <module>
    from . import stone_validators as bv
  File "/home/zubair/.local/share/screencloud/ScreenCloud/plugins/dropbox/modules/dropbox/stone_validators.py", line 21, in <module>
    from typing import Optional
ImportError: No module named 'typing'
`

Any help on how to resolve it?

Thanks
