### ISSUE TITLE
NextCloud integration

### ISSUE THREAD

**Issue by cb3inco** [olav-st/screencloud#316]
Allow images to be saved to a nextcloud location and generate shared links.

**Comment by enerow** [comment]
Would be great!

**Comment by olav-st** [comment]
Not sure how different NextCloud and OwnCloud have become, but could this work? https://github.com/Section214/screencloud-owncloud

**Comment by chodorenko** [comment]
Its Plugin not work now 
https://github.com/Section214/screencloud-owncloud/issues/2


Test On Linux which AppImage

Traceback (most recent call last):
File "", line 90, in startAuthenticationProcess
AttributeError: 'module' object has no attribute 'Client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 102, in startAuthenticationProcess
AttributeError: 'AttributeError' object has no attribute 'message'

**Comment by tmiland** [comment]
Hi, 
i forked and customized the owncloud repo for NextCloud: https://github.com/tmiland/screencloud-nextcloud

They both work with ScreenCloud 1.3.0. Follow the link for Installation instructions. 🤓

**Comment by olav-st** [comment]
@tmiland Thanks for this! 🙌

**Comment by cantalupo555** [comment]
@tmiland Interesting

**Comment by cantalupo555** [comment]
@tmiland How to install this module?

**Comment by tmiland** [comment]
> @tmiland Thanks for this! raised_hands

My pleasure! 😃

Any plans to bump the ScreenCloud version in the repos? 😇

> @tmiland How to install this module?

Follow the link. 😎

**Comment by XeroxDev** [comment]
Hey @tmiland 

I tried your Version but with the latest ScreenCloud Version (1.4.0) it's not working. ScreenCloud says it's not configured and I think it's because of the connection status, but if I try to press it, nothing happens. After 5 Minutes status is still unchanged and says "Unknown". I would be very happy, if you can update it.

Kind regards,
XeroxDev

**Comment by tmiland** [comment]
> Hey @tmiland
> 
> I tried your Version but with the latest ScreenCloud Version (1.4.0) it's not working. ScreenCloud says it's not configured and I think it's because of the connection status, but if I try to press it, nothing happens. After 5 Minutes status is still unchanged and says "Unknown". I would be very happy, if you can update it.
> 
> Kind regards,
> XeroxDev

Hi,

just follow the instructions to get it working. 🙂

Regards

**Comment by XeroxDev** [comment]
Hey @tmiland 

I followed the instructions, but it still won't work. And much to setup isn't there. And filling out Url, username and password isn't that hard ;) 

Here a screenshot, maybe you see the problem.
![d943363ce470a842af32a720e9a4586e](https://user-images.githubusercontent.com/10864620/54038194-3a59ca00-41c0-11e9-8845-2d4800ae41c4.png)

**Comment by tmiland** [comment]
> Hey @tmiland
> 
> I followed the instructions, but it still won't work. And much to setup isn't there. And filling out Url, username and password isn't that hard ;)
> 
> Here a screenshot, maybe you see the problem.
> ![d943363ce470a842af32a720e9a4586e](https://user-images.githubusercontent.com/10864620/54038194-3a59ca00-41c0-11e9-8845-2d4800ae41c4.png)

You installed 1.3.0 from the repo? If not, you are probably missing dependencies. 

I just tried 1.4.0, both appimage and snap did not work. 🙂

What version of nextcloud are you on?

**Comment by XeroxDev** [comment]
@tmiland 

My ScreenCloud Version is 1.4.0 (latest)
and my NextCloud Version is 15.0.5 (latest)

**Comment by tmiland** [comment]
> @tmiland
> 
> My ScreenCloud Version is 1.4.0 (latest)
> and my NextCloud Version is 15.0.5 (latest)

That ain't gonna work. What you could try, is to install 1.3.0 from the repo, then upgrade to latest.

It will install missing dependencies.

**Comment by XeroxDev** [comment]
> > @tmiland
> > My ScreenCloud Version is 1.4.0 (latest)
> > and my NextCloud Version is 15.0.5 (latest)
> 
> That ain't gonna work. What you could try, is to install 1.3.0 from the repo, then upgrade to latest.
> 
> It will install missing dependencies.
> 
> Edit: I haven't tested this on windows.

Maybe it's a stupid windows bug? Maybe you can bring it to work for windows. Cause of my work I'm bound to windows ._.

**Comment by tmiland** [comment]
> > > @tmiland
> > > My ScreenCloud Version is 1.4.0 (latest)
> > > and my NextCloud Version is 15.0.5 (latest)
> > 
> > 
> > That ain't gonna work. What you could try, is to install 1.3.0 from the repo, then upgrade to latest.
> > It will install missing dependencies.
> > Edit: I haven't tested this on windows.
> 
> Maybe it's a stupid windows bug? Maybe you can bring it to work for windows. Cause of my work I'm bound to windows ._.
> 
> And maybe you can keep me up to date, if you really try to fix this for windows @tmiland :D

Maybe. 😂 

Well, i deleted all my windows installations for privacy reasons, but i'll try to get it going on a virtual install and see what happens. 🤓

**Comment by XeroxDev** [comment]
> Well, i deleted all my windows installations for privacy reasons

Understandable 😂



> but i'll try to get it going on a virtual install and see what happens. 🤓

Ok, thanks :D Maybe it's only something small :D

**Comment by XeroxDev** [comment]
Oh and @tmiland Maybe it's help you, if I send you the traceback :D

```
Traceback (most recent call last):
  File "<string>", line 90, in startAuthenticationProcess
AttributeError: module 'nextcloud' has no attribute 'Client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 102, in startAuthenticationProcess
AttributeError: 'AttributeError' object has no attribute 'message'
```

**Comment by tmiland** [comment]
Did some testing now, not working on 1.3.0 or 1.4.0 on windows. 

Feel free to open a pull request in the repo if you are able get it working. 👍

**Comment by XeroxDev** [comment]
@tmiland Oh.. I see... Can it be, that you did nothing but changed all "owncloud" strings into "nextcloud"? ;)

**Comment by XeroxDev** [comment]
@olav-st I'll hope you are deciding to implement it officially to screencloud or fork the old plugin, repair it and make it a officially plugin? :D

I'm not so into python, I'm more so javascript / typescript :D
